### ISSUE TITLE
Change implementation of FSharpPlus.Internals.Id<'t> to a DU to improve perf and reduce heap allocations

### ISSUE THREAD

**Issue by chinwobble** [gusty/FSharpPlus#96]
### Description

Running the following micro-benchmarks revealed that we can improve perf just by switching to a FSharpPlus.Internals.Id<'t> to a DU.

### Repro steps

Please provide the steps required to reproduce the problem

Run the following code in release mode 

```
open System
open BenchmarkDotNet
open BenchmarkDotNet.Running
open BenchmarkDotNet.Attributes

type Id<'t>(v:'t) =
   let value = v
   member __.getValue = value

[<RequireQualifiedAccess>]
module Id =
    let run   (x:Id<_>) = x.getValue
    let map f (x:Id<_>) = Id (f x.getValue)
    let create x = Id (x)

type IdDU<'t> =
   | Value of 't
[<RequireQualifiedAccess>]
module IdDU =
    let run (x:IdDU<_>) = match x with  | Value x -> x
    let map f (x:IdDU<_>) = IdDU.Value (f <| run x)
    let create x = IdDU.Value x // probably unnecessary

[<Attributes.MemoryDiagnoserAttribute>]
type RunBenchmark() =
    [<BenchmarkAttribute()>]
    member __.RunClass (): int = 
        Id.run(Id(100))

    [<BenchmarkAttribute>]
    member __.RunDiscimrinatedUnion (): int = 
        IdDU.run (IdDU.Value( 100))

[<EntryPoint>]
let main argv =
    let benchmarks = 
        [|
            //typeof<RunBenchmark>
            typeof<CreateBenchmark>
            //typeof<MapBenchmarks>
        |] 
        |> Array.map BenchmarkConverter.TypeToBenchmarks

    BenchmarkRunner.Run(benchmarks) |> ignore
    
    0 // return an integer exit code

```

Results:

|Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
|---------------------- |----------:|----------:|----------:|-------:|----------:|
|              RunClass | 3.0804 ns | 0.0946 ns | 0.1052 ns | 0.0076 |      24 B |
| RunDiscimrinatedUnion | 0.0034 ns | 0.0063 ns | 0.0059 ns |      - |       0 B |

### Related information 

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.309)
Intel Core i5-3570K CPU 3.40GHz (Ivy Bridge), 1 CPU, 4 logical cores and 4 physical cores
Frequency=3320335 Hz, Resolution=301.1744 ns, Timer=TSC
.NET Core SDK=2.1.101
  [Host] : .NET Core 2.0.6 (CoreCLR 4.6.26212.01, CoreFX 4.6.26212.01), 64bit RyuJIT DEBUG

**Comment by gusty** [comment]
Thanks for the thorough analysis.

But this type (and all the types in Internals under ``// Dummy types``) is not really used at run-time.

The sole purpose of these types is to make the compiler happy at the overload resolution, they introduce the necessary ambiguity to prevent the F# compiler to resolve overload early.

The `Id` abstraction that is really used (for instance to construct lenses) is ``Identity<'T>`` in ``FSharp.Data`` and it is already a DU.

However one open question is whether this and other abstraction (Reader, Writer) which are already DUs should compile as a struct or not.

They were switched recently to struct DUs because it seems to make more sense as they are all wrappers, but it would be nice to have a benchmark like this to support that claim (or eventually prove it wrong). Here is the issue: https://github.com/gusty/FSharpPlus/issues/77 you can add your comments there.

Off topic, I wonder why there is such difference between class and DUs when that specific DUs you were benchmarking is also compiled to a class. Is it because of the sealed attribute?

**Comment by chinwobble** [comment]
Regarding the DU vs Class issue I noticed that as well since DU are compiled to classes.

I suspect there may be some compilation optimisation occurring for DUs.

**Comment by wallymathieu** [comment]
Can we close this issue @chinwobble ?

**Comment by chinwobble** [comment]
@wallymathieu sure you can close it.
