### ISSUE TITLE
Possibly create a ChoiceT Monad Transformer

### ISSUE THREAD

**Issue by Tombert** [gusty/FSharpPlus#99]
### Description

While I do see a `ResultT` transformer, several .NET libraries still use the (admittedly outdated) `Choice` type (e.g. `Async.Catch`).  The `Choice` type is incompatible with the `Result` type. 

### Repro steps

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Known workarounds

I suppose I could create a function called `choiceToResult` like this

```
let choiceToResult myThingy =
    match myThingy with
    | Choice1Of2 x -> Ok x
    | Choice2Of2 ex -> Error ex
```
However, this is a bit clunky since I'd have to pipe every `Choice` result into this function.

**Comment by wallymathieu** [comment]
There is this existing issue #52

**Comment by gusty** [comment]
Creating a ``ChoiceT`` may seem as easy as to copy-paste ``ResultT`` and replace ``Result`` with ``Choice`` but there are other implications: ``ResultT`` works with our [MonadError](https://github.com/gusty/FSharpPlus/blob/master/src/FSharpPlus/MonadTrans.fs#L25-L44) abstraction, which by looking at the code should also work in theory with ``Choice``.

We can test this approach by trying to re-write some [sample code](https://github.com/gusty/FSharpPlus/blob/master/docsrc/content/abstraction-monad.fsx#L159-L175) with ChoiceT

Otherwise it should be straight-forward to create an ``Async.Catch`` version that creates a ``Result`` instead of a ``Choice``, we can call it ``Async.CatchToResult``.

**Comment by wallymathieu** [comment]
Sounds like a nice thing for a pull request 😉 @Tombert

**Comment by wallymathieu** [comment]
I will start to look into making a PR for it @Tombert . We can pair on it if you want.
